dist: trusty
sudo: false
language: generic
services:
  - docker
branches:
  only:
    - master
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh
    --output-document miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config
    --set always_yes yes
    --set changeps1 no
  - wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.4.0d/linux-pandoc_2_7.tar.gz --output-document pandoc-crossref.tar.gz
  - tar xvfz pandoc-crossref.tar.gz
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - conda env create --quiet --file build/environment.yml
  - conda list --name manubot
  - conda activate manubot
  - apt-get install ghc cabal-install
script:
  - sh build/build.sh
cache:
  directories:
    - ci/cache
    - $HOME/.stack
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_EVENT_TYPE = "push" &&
    sh ci/deploy.sh
